name: Swarm CI/CD Pipeline

on:
  push:
    branches:
      - main

# GHCR (GitHub İmaj Deposu) üzerine yazma izni
permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: 1. Repoyu Çek
        uses: actions/checkout@v4

      - name: 2. GitHub Registry'ye Giriş (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: 3. İmajı Derle
        run: docker build -t ghcr.io/sarikayaatakan/swarm-cicd-demo:latest .

      - name: 4. İmajı GHCR'a Yükle
        run: docker push ghcr.io/sarikayaatakan/swarm-cicd-demo:latest

      - name: 5. Swarm Servisini Güncelle veya Başlat
        run: |
          if ! docker service inspect my-web-app > /dev/null 2>&1; then
            docker service create --name my-web-app --replicas 2 -p 8080:80 --with-registry-auth ghcr.io/sarikayaatakan/swarm-cicd-demo:latest
          else
            docker service update --image ghcr.io/sarikayaatakan/swarm-cicd-demo:latest --with-registry-auth --force my-web-app
          fi
